filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
repositories:
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: dev
  url: http://chartmuseum-jx.35.232.140.43.nip.io/
releases:
- chart: jx3/jx-verify
  name: jx-verify
  namespace: jx-staging
  values:
  - jx-values.yaml
- chart: dev/go-demo
  version: 0.0.1
  name: go-demo
  namespace: jx-staging
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
