apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: garroshh
    provider: github
    repository: go-demo
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: garroshh-go-demo
  namespace: jx
spec:
  httpCloneURL: https://github.com/garroshh/go-demo.git
  org: garroshh
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: go-demo
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/garroshh/go-demo
